Steam/Steam/urls.py
from django.contrib import admin
from django.contrib.auth.views import login, logout
from steam_app import views
from django.conf.urls import url, include

urlpatterns = (
    url(r'^$', login, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^accounts/login/$', login, name='login'),
    url(r'^accounts/profile/$', views.mainpage, name='mainpage'),
    url(r'^game/$', views.games, name='game'),
    url(r'^user/$', views.user, name='user'),
    url(r'^change/user/(?P<id_user>\d+)/$', views.change_user, name='change_user'),
    url(r'^change/user/(?P<id_user>\d+)/delete/$', views.delete_user, name='delete_user'),
    url(r'^list/users/$', views.print_users, name='print_users'),
    url(r'^change/user/done/$', views.after_change_user, name='after_change_user'),
    url(r'^user/sent/$', views.after_user, name='user_sent'),
    url(r'^change/game/(?P<id_game>\d+)/$', views.change_game,  name='change_game'),
    url(r'^change/game/(?P<id_game>\d+)/delete/$', views.delete_game,  name='delete_game'),
    url(r'^list/games/$', views.print_games, name='print_game'),
    url(r'^change/game/done/$', views.after_change_game, name='after_change_game'),
    url(r'^game/sent/$', views.after_game, name='game_sent'),
    url(r'^clan/$', views.clan, name='clan'),
    url(r'^clan/sent/$', views.after_clan, name='clan_sent'),
    url(r'^list/clans/$', views.print_clan, name='print_clan'),
    url(r'^change/clan/(?P<id_clan>\d+)/$', views.change_clan,  name='change_clan'),
    url(r'^change/clan/(?P<id_clan>\d+)/delete/$', views.delete_clan,  name='delete_clan'),
    url(r'^change/clan/done/$', views.after_change_clan, name='after_change_clan'),
    url(r'^achievement/$', views.achievement, name='achievement'),
    url(r'^achievement/sent/$', views.after_achievement, name='achievement_sent'),
    url(r'^list/achievement/$', views.print_achievement, name='print_achievement'),
    url(r'^change/achievement/(?P<id_achievement>\d+)/$', views.change_achievement, name='change_achievement'),
    url(r'^change/achievement/(?P<id_achievement>\d+)/delete/$', views.delete_achievement, name='delete_achievement'),
    url(r'^change/achievement/done/$', views.after_change_achievement, name='after_change_achievement'),
    url(r'^logout/$', logout, {'template_name': 'logout.html'}, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include('steam_app.urls')),
)

Steam/steam_app/urls.py
from django.conf.urls import  url
import views
from views import APIUserProfileList, APIUserProfileDetail


urlpatterns = (
    url(r'^$', views.api_page, name='api_page'),
    url(r'^userprofile/$', APIUserProfileList.as_view(), name='userprofile-list'),
    url(r'^userprofile/(?P<pk>\d+)/$', APIUserProfileDetail.as_view(), name='userprofile-detail'),
    url(r'^game/$', views.APIGameList.as_view(), name='game-list'),
    url(r'^game/(?P<pk>\d+)/$', views.APIGameDetail.as_view(), name='game-detail'),
    url(r'^achievement/$', views.APIAchievementList.as_view(), name='achievement-list'),
    url(r'^achievement/(?P<pk>\d+)/$', views.APIAchievementDetail.as_view(), name='achievement-detail'),
    url(r'^clan/$', views.APIClanList.as_view(), name='clan-list'),
    url(r'^clan/(?P<pk>\d+)/$', views.APIClanDetail.as_view(), name='clan-detail'),
)

Steam/steam_app/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class UserProfile(models.Model):
    user = models.OneToOneField(User, unique=True)
    steam_id = models.IntegerField(unique=True,default=False)
    nickname = models.CharField(max_length=50, default='' , unique=True)
    real_name=models.CharField(max_length=50,blank=True, null=True)
    city = models.CharField(max_length=50, default='')
    stateOrProvince = models.CharField(max_length=50, blank=True, null=True)
    country=models.CharField(max_length=50, blank=True, null=True)
    url_profile=models.CharField(max_length=50, blank=True, null=True)
    #avatar=models.CharField(max_length=50, blank=True, null=True)
    friends=models.TextField(null=True, blank=True) #Para poder poner amigos que no esten registrados a nuestra app
    def get_absolute_url(self):
        return reverse('change_name', kwargs={'id_game': self.id})

    def __unicode__(self):
        return str(self.user.username)

class Game (models.Model):
    user = models.ForeignKey(User)
    appid = models.IntegerField(default=False)
    name = models.CharField(max_length=50, default='')
    version= models.FloatField(blank=True, null=True)
    company=models.CharField(max_length=50, blank=True, null=True)
    opinion = models.TextField(blank=True, null=True)
    def get_absolute_url(self):
        return reverse('change_name', kwargs={'id_game': self.id})
    def __unicode__(self):
        return str( "Juego: " + str(self.name))

class Achievement(models.Model):

    user = models.ForeignKey(User)
    appid_game = models.ForeignKey(Game, default=False)
    name = models.CharField(max_length=50, default='')
    achieved = models.BooleanField(default=False)
    def get_absolute_url(self):
        return reverse('change_achievement', kwargs={'id_achievement': self.id})
    def __unicode__(self):
        return str("Usuario: " + str(self.user) + "," + "Achievement: "+ str(self.name))


class Clan(models.Model):
    user = models.ForeignKey(User)
    name = models.CharField(max_length=50, default='')
    number_of_person=models.IntegerField(blank=True, null=True)
    members = models.TextField(null=True, blank=True) #Para poder poner miembros que no esten regitrados a nuestra app
    def get_absolute_url(self):
        return reverse('change_clan', kwargs={'id_clan': self.id})
    def __unicode__(self):
        return str("Clan:" + self.name )

Steam/steam_app/forms.py
from django import forms
from django.contrib.auth.models import User
from models import Game, Clan, Achievement, UserProfile
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password')

class GameForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = ('user', 'id','appid', 'name','version', 'company', 'opinion')
        exclude = ('user', 'id', )

class ClanForm (forms.ModelForm):
    class Meta:
        model = Clan
        fields = ('user', 'id', 'name','number_of_person','members')
        exclude = ('user', 'id')
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields=('user','id','steam_id','nickname','real_name','city','stateOrProvince','country','url_profile','friends')
        exclude = ('user','id')
class AchievementForm (forms.ModelForm):
    class Meta:
        model = Achievement
        fields = ('user', 'id', 'appid_game','name','achieved')
        exclude = ('user', 'id')

Steam/steam_app/views.py
# Create your views here.
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, render_to_response, get_object_or_404
from django.template import RequestContext
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt
from rest_framework import permissions, generics

import forms
from serializers import UserProfileSerializer, GameSerializer, AchievementSerializer, ClanSerializer
from forms import UserForm, GameForm, ClanForm, AchievementForm
from models import UserProfile, Game, Clan, Achievement


@csrf_exempt
def register(request):

    context = RequestContext(request)


    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)


        if user_form.is_valid():

            user = user_form.save()

            user.set_password(user.password)
            user.save()

            registered = True

        else:
            print user_form.errors
    else:
        user_form = UserForm()

    # Render the template depending on the context.
    return render_to_response(
        'registration/register.html',
        {'user_form': user_form, 'registered': registered},
        context)
@login_required
def mainpage(request):

    context = RequestContext(request)
    return render_to_response("mainpage.html",{}, context)

def after_logout(request):
    context = RequestContext(request)
    return render_to_response("logout.html", {}, context)
@csrf_exempt
@login_required()
def games(request):
    if request.method=="POST":
        GameForm=forms.GameForm(data=request.POST)
        if GameForm.is_valid():
            game = Game(user=request.user, appid=GameForm.cleaned_data['appid'],name=GameForm.cleaned_data['name'],
                             version=GameForm.cleaned_data['version'], company=GameForm.cleaned_data['company'],
                             opinion=GameForm.cleaned_data['opinion'])
            game.save()
            return HttpResponseRedirect('/game/sent')
        else:
            print(GameForm.errors)
    else:
        GameForm=forms.GameForm()

    return render(request,"game.html", {'GameForm':GameForm})
@login_required
def print_games(request):
    l = []
    u = User.objects.get(username__exact=request.user)
    for i in Game.objects.all():
        if i.user == u:
            l.append(i)
    return render(request, "list_game.html", {'list': l})
@csrf_exempt
@login_required
def change_game(request, id_game):
    game = get_object_or_404(Game, pk=id_game)
    if request.method == "POST":
        game_form = forms.GameForm(request.POST, instance=game)
        if game_form.is_valid():
            game_form.save()
            return HttpResponseRedirect('/change/game/done')
        else:
            game = Game.objects.get(pk=id_game)
            GameForm = forms.GameForm(instance=game)
    else:
        GameForm = forms.GameForm(instance=game)

    return render(request, "edit_game.html", {'GameForm': GameForm})
@login_required
def delete_game(request, id_game):
    game = Game.objects.get(pk=id_game)
    game.delete()
    return render(request, "delete_game.html", {})
@login_required
def after_change_game(request):
    context = RequestContext(request)
    return render_to_response("update_game.html", {}, context)
@login_required
def after_game(request):
    context = RequestContext(request)
    return render_to_response("game_created.html", {}, context)

@csrf_exempt
@login_required
def clan(request):
    if request.method=="POST":
        ClanForm=forms.ClanForm(data=request.POST)
        if ClanForm.is_valid():
            clan = Clan(user=request.user,name=ClanForm.cleaned_data['name'],
                             number_of_person=ClanForm.cleaned_data['number_of_person'],
                            members=ClanForm.cleaned_data['members']
                             )
            clan.save()
            return HttpResponseRedirect('/clan/sent')
        else:
            print(ClanForm.errors)
    else:
        ClanForm=forms.ClanForm()

    return render(request,"clan.html", {'ClanForm':ClanForm})
@csrf_exempt
@login_required
def after_clan(request):
    context = RequestContext(request)
    return render_to_response("clan_created.html", {}, context)
@login_required
def print_clan(request):
    l = []
    u = User.objects.get(username__exact=request.user)
    for i in Clan.objects.all():
        if i.user == u:
            l.append(i)
    return render(request, "list_clan.html", {'list': l})
@csrf_exempt
@login_required
def change_clan(request, id_clan):
    clan = get_object_or_404(Clan, pk=id_clan)
    if request.method == "POST":
        clan_form = forms.ClanForm(request.POST, instance=clan)
        if clan_form.is_valid():
            clan_form.save()
            return HttpResponseRedirect('/change/clan/done')
        else:
            clan = Clan.objects.get(pk=id_clan)
            ClanForm = forms.ClanForm(instance=clan)
    else:
        ClanForm = forms.ClanForm(instance=clan)

    return render(request, "edit_clan.html", {'ClanForm': ClanForm})
@csrf_exempt
@login_required
def delete_clan(request, id_clan):
    clan = Clan.objects.get(pk=id_clan)
    clan.delete()
    return render(request, "delete_clan.html", {})
@csrf_exempt
@login_required
def after_change_clan(request):
    context = RequestContext(request)
    return render_to_response("update_clan.html", {}, context)


@csrf_exempt
@login_required
def achievement(request):
    achi = AchievementForm(data=request.POST)
    achi.fields['appid_game'].queryset = Game.objects.filter(user=request.user)
    if request.method=="POST":
        if achi.is_valid():
            achievement = Achievement(user=request.user,name= achi.cleaned_data['name'],
                             appid_game=(achi.cleaned_data['appid_game']),
                            achieved=achi.cleaned_data['achieved']
                             )
            achievement.save()
            return HttpResponseRedirect('/achievement/sent')
        else:
            print(achi.errors)
    else:
        achievement=achi

    return render(request,"Achievements.html", {'AchievementForm':achievement})
@csrf_exempt
@login_required
def after_achievement(request):
    context = RequestContext(request)
    return render_to_response("achievement_created.html", {}, context)
@login_required
def print_achievement(request):
    l = []
    u = User.objects.get(username__exact=request.user)
    for i in Achievement.objects.all():
        if i.user == u:
            l.append(i)
    return render(request, "list_achievement.html", {'list': l})
@csrf_exempt
@login_required
def change_achievement(request, id_achievement):
    achievement = get_object_or_404(Achievement, pk=id_achievement)
    if request.method == "POST":
        achievement_form = forms.AchievementForm(request.POST, instance=achievement)
        if achievement_form.is_valid():
            achievement_form.save()
            return HttpResponseRedirect('/change/achievement/done')
        else:
            achievement = Achievement.objects.get(pk=id_achievement)
            AchievementForm = forms.AchievementForm(instance=achievement)
    else:
        AchievementForm = forms.AchievementForm(instance=achievement)

    return render(request, "edit_achievement.html", {'AchievementForm': AchievementForm})
@csrf_exempt
@login_required
def delete_achievement(request, id_achievement):
    achievement = Achievement.objects.get(pk=id_achievement)
    achievement.delete()
    return render(request, "delete_achievement.html", {})
@csrf_exempt
@login_required
def after_change_achievement(request):
    context = RequestContext(request)
    return render_to_response("update_achievement.html", {}, context)
@login_required
def user(request):
    if request.method=="POST":
        UserForm=forms.UserProfileForm(data=request.POST)
        if UserForm.is_valid():
            user = UserProfile(user=request.user, steam_id=UserForm.cleaned_data['steam_id'],nickname=UserForm.cleaned_data['nickname'],
                             real_name=UserForm.cleaned_data['real_name'],city=UserForm.cleaned_data['city'],stateOrProvince=UserForm.cleaned_data['stateOrProvince'], country=UserForm.cleaned_data['country'],
                         friends=UserForm.cleaned_data['friends'])
            user.save()
            return HttpResponseRedirect('/user/sent')
        else:
            print(UserForm.errors)
    else:
        UserForm=forms.UserProfileForm()

    return render(request,"user.html", {'UserForm':UserForm})
@login_required
def after_user(request):
    context = RequestContext(request)
    return render_to_response("user_created.html", {}, context)
@login_required
def print_users(request):
    l = []
    u = User.objects.get(username__exact=request.user)
    for i in UserProfile.objects.all():
        if i.user == u:
            l.append(i)
    return render(request, "list_user.html", {'list': l})
@login_required
def change_user(request, id_user):
    user = get_object_or_404(UserProfile, pk=id_user)
    if request.method == "POST":
        user_form = forms.UserProfileForm(request.POST, instance=user)
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect('/change/user/done')
        else:
            user = UserProfile.objects.get(pk=id_user)
            UserProfileForm = forms.UserProfileForm(instance=user)
    else:
        UserProfileForm = forms.UserProfileForm(instance=user)
    return render(request, "edit_user.html", {'UserProfileForm': UserProfileForm})
@login_required
def after_change_user(request):
    context = RequestContext(request)
    return render_to_response("update_user.html", {}, context)
@login_required
def delete_user(request, id_user):
    user = UserProfile.objects.get(pk=id_user)
    user.delete()
    return render(request, "delete_user.html", {})
@login_required
def api_page(request):

Steam/steam_app/templates/after_login.html
<!DOCTYPE html>
<meta charset="UTF-8">
{% load staticfiles %}
<html lang="en"> <head>
<link rel="stylesheet" href="{% static "style/base.css" %}" />
<title>{% block title %}Thanks to visit Steam_app!{% endblock %}</title> </head>
<body>
<div id="header">
<Strong>Thanks for visit this app</Strong>
<div id="sidebar">
{% block sidebar %}<ul><li><a href="/logout/">Logout</a></li></ul>{% endblock %} </div>
    <ul><li><a href="/game/">Game</a></li></ul> </div>
    <ul><li><a href="/clan/">Clan</a></li></ul> </div>
{% block content %}
{% endblock %}
<div id="footer">{% block footer %}{% endblock %}</div> </body>
</html>

Steam/steam_app/templates/api.html
<!DOCTYPE html>
<body style="background:#cef9f9">

<div id="content">
    <h2 ALIGN=center>
       <br> <h1 ALIGN=center><strong>API RESTFUL</strong><br/>
    <br><a href="/api/userprofile">API User profile</a> <br/>
    <br><a href="/api/game">API Game</a> <br/>
        <br><a href="/api/achievement">API Achievements</a> <br/>
        <br><a href="/api/clan">API Clan</a> <br/>
</h1>

    </h2>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
</div>

</body>
</html>

Steam/steam_app/templates/clan.html
{%  extends "base.html" %}

{% block content %}

<div class="text-center">
    <h1 ALIGN=center><strong>Create a clan!</strong></h1>
</div>
    <form method="post"  enctype="multipart/form-data">
        {% csrf_token %}
        <table ALIGN=center>
        {{ ClanForm.as_table }}
        </table>
        <h1 ALIGN=center> <input type="submit" name="submit" value="Guardar"/></h1>

    </form>


{% endblock %}

Steam/steam_app/templates/delete_clan.html
{%extends "base.html" %}
{% csrf_token %}
{% block content %}


    <style>
    .message1{
        margin-top: 120px;
    }
    </style>
    <style>
    .message2{
        margin-top: 30px;
    }
    </style>

    <div class="message1 text-center">
        <h1><strong> The changes have been applied! </strong></h1>
</div>
<div class="message2 text-center">
    <h2>Check out the new details in your Profile</h2>
        <a href="/accounts/profile">Return to Homepage</a>
</div>

{% endblock %}

Steam/steam_app/templates/delete_game.html
{%extends "base.html" %}
{% csrf_token %}
{% block content %}


    <style>
    .message1{
        margin-top: 120px;
    }
    </style>
    <style>
    .message2{
        margin-top: 30px;
    }
    </style>

    <div class="message1 text-center">
        <h1><strong> The changes have been applied! </strong></h1>
</div>
<div class="message2 text-center">
    <h2>Check out the new details in your Profile</h2>
        <a href="/accounts/profile">Return to Homepage</a>
</div>

{% endblock %}

Steam/steam_app/templates/delete_user.html
{%extends "base.html" %}
{% csrf_token %}
{% block content %}


    <style>
    .message1{
        margin-top: 120px;
    }
    </style>
    <style>
    .message2{
        margin-top: 30px;
    }
    </style>

    <div class="message1 text-center">
        <h1><strong> The changes have been applied! </strong></h1>
</div>
<div class="message2 text-center">
    <h2>Check out the new details in your Profile</h2>
        <a href="/accounts/profile">Return to Homepage</a>
</div>

{% endblock %}

Steam/steam_app/templates/edit_user.html
{%  extends "base.html" %}

{% block content %}
<head>
    {% load staticfiles %}

    <script>
        $(function() {
            $.getJSON("{% static "countries.json" %}", {}, function (countries) {
                $("#id_country").autocomplete({
                    source: countries
                });
            });

            $("#id_city").autocomplete({
                source: function( request, response ) {
                    $.ajax({
                        url: "http://ws.geonames.org/searchJSON",
                        dataType: "jsonp",
                        data: {
                            featureClass: "P",
                            maxRows: 10,
                            name_startsWith: request.term,
                            username: "demo"
                        },
                        success: function( data ) {
                            response( $.map( data.geonames, function( item ) {
                                return {
                                    label: item.name + (item.adminName1 ? ", " + item.adminName1 : "") + ", " + item.countryName,
                                    value: item.name,
                                    stateOrProvince: item.adminName1,
                                    countryName: item.countryName
                                }
                            }));
                        }
                    });
                },
                minLength: 2,
                select: function( event, ui ) {
                    if (ui.item) {
                        $("#id_stateOrProvince").val(ui.item.stateOrProvince);
                        $("#id_country").val(ui.item.countryName);
                        $("#id_zipCode").val("");
                    }
                }
            });
        });
    </script>
<div class="text-center">
    <h1 ALIGN=center><strong>Edit user profile!</strong></h1>
</div>
    <form method="post"  enctype="multipart/form-data">
        {% csrf_token %}
        <table ALIGN=center>
        {{ UserProfileForm.as_table }}
        </table>
        <h1 ALIGN=center> <input type="submit" name="submit" value="Guardar"/></h1>


    </form>


{% endblock %}

Steam/steam_app/templates/game_created.html
<html>
<meta charset="UTF-8">
{% load staticfiles %}
<html lang="en"> <head>
<link rel="stylesheet" href="{% static "style/base.css" %}" />
<title>{% block title %}Thanks to create a game!{% endblock %}</title> </head>
<body style="background:#cef9f9">
<div id="header">
    <h1 ALIGN=center><Strong ALIGN=center>Thanks to create a game!</Strong></h1>
<div id="sidebar">
{% block sidebar %} <h1 ALIGN=center><br ><a href="/accounts/profile">Return homepage</a> <br/></h1>{% endblock %} </div>
{% block content %}
{% endblock %}
<div id="footer">{% block footer %}{% endblock %}</div>
</body>
</html>

Steam/steam_app/templates/list_achievement.html
{%extends "base.html" %}
{% block content %}
<div P ALIGN="center">
    <h1>List of achievements</h1>
</div>

     <style>
    .opinions_table{
        margin-left:100px;
        margin-right:150px;
        margin-top: 50px;
    }
    </style>
    <div class="opinions_table">
    <table border="5px" style="background:#ebddf9">
            <tr>
                <th >ID_ACHIEVEMENT </th>
                <th >NAME </th>
                <th >APPID_GAME </th>
                <th >ACHIEVED </th>

            </tr>
    {% for i in list %}
            <tr>
                <section vocab ="http://schema.org/" typeof = "AchieveAction">
                    <td><span property="identifier">{{ i.id }}</span> </td>
                    <td width="10%"><span property="name">{{ i.name }}</span></td>
                </section>
                <section vocab ="http://schema.org/" typeof = "Game">

                        <td width="15%"><span property="identifier">{{ i.appid_game }}</span></td>
                        <td width="15%">{{ i.achieved }}</td>
                 </section>
                <td><br><a href="{% url 'change_achievement' id_achievement=i.id %}">Edit your achievement!</a> <br/></td>
                <td><br><a href="{% url 'delete_achievement' id_achievement=i.id %}">Delete your achievement!</a> <br/></td>
            </tr>
    {% endfor %}

        </table>
    </div>
{% endblock %}

Steam/steam_app/templates/list_game.html
{%extends "base.html" %}
{% block content %}
<div P ALIGN="center">
    <h1>List of games</h1>
</div>

     <style>
    .opinions_table{
        margin-left:100px;
        margin-right:150px;
        margin-top: 50px;
    }
    </style>
    <div class="opinions_table">
    <table border="5px" style="background:#ebddf9">
            <tr>
                <th >ID_GAME </th>
                <th >NAME </th>
                <th >VERSION </th>
                <th >COMPANY </th>
                <th >OPINIONS </th>
            </tr>
    {% for i in list %}
            <tr>
                <section vocab ="http://schema.org/" typeof = "Game">
                    <td><span property="identifier">{{ i.appid }}</span></td>
                    <td width="10%"><span property="name">{{ i.name }}</span> </td>
                    <td width="15%"><span property="version">{{ i.version }}</span></td>
                    <td width="15%"><span property="publisher">{{ i.company }}</span></td>
                    <td width="70%"><span property="comment">{{ i.opinion }}</span></td>
                </section>
                <td><br><a href="{% url 'change_game' id_game=i.id %}">Edit your game!</a> <br/></td>
                <td><br><a href="{% url 'delete_game' id_game=i.id %}">Delete your game!</a> <br/></td>
            </tr>
    {% endfor %}

        </table>
    </div>
{% endblock %}

Steam/steam_app/templates/update_clan.html
{%extends "base.html" %}
{% csrf_token %}
{% block content %}


    <style>
    .message1{
        margin-top: 120px;
    }
    </style>
    <style>
    .message2{
        margin-top: 30px;
    }
    </style>

    <div class="message1 text-center">
        <h1><strong> The changes have been applied! </strong></h1>
</div>
<div class="message2 text-center">
    <h2>Check out the new details in your Profile</h2>
        <a href="/accounts/profile">Return to Homepage</a>
</div>

{% endblock %}

Steam/steam_app/templates/update_game.html
{%extends "base.html" %}
{% csrf_token %}
{% block content %}


    <style>
    .message1{
        margin-top: 120px;
    }
    </style>
    <style>
    .message2{
        margin-top: 30px;
    }
    </style>

    <div class="message1 text-center">
        <h1><strong> The changes have been applied! </strong></h1>
</div>
<div class="message2 text-center">
    <h2>Check out the new details in your Profile</h2>
        <a href="/accounts/profile">Return to Homepage</a>
</div>

{% endblock %}

Steam/steam_app/templates/update_user.html
{%extends "base.html" %}
{% csrf_token %}
{% block content %}


    <style>
    .message1{
        margin-top: 120px;
    }
    </style>
    <style>
    .message2{
        margin-top: 30px;
    }
    </style>

    <div class="message1 text-center">
        <h1><strong> The changes have been applied! </strong></h1>
</div>
<div class="message2 text-center">
    <h2>Check out the new details in your Profile</h2>
        <a href="/accounts/profile">Return to Homepage</a>
</div>

{% endblock %}

Steam/steam_app/templates/user.html
{%  extends "base.html" %}

{% block content %}
<head>
    {% load staticfiles %}

    <script>
        $(function() {
            $.getJSON("{% static "countries.json" %}", {}, function (countries) {
                $("#id_country").autocomplete({
                    source: countries
                });
            });

            $("#id_city").autocomplete({
                source: function( request, response ) {
                    $.ajax({
                        url: "http://ws.geonames.org/searchJSON",
                        dataType: "jsonp",
                        data: {
                            featureClass: "P",
                            maxRows: 10,
                            name_startsWith: request.term,
                            username: "demo"
                        },
                        success: function( data ) {
                            response( $.map( data.geonames, function( item ) {
                                return {
                                    label: item.name + (item.adminName1 ? ", " + item.adminName1 : "") + ", " + item.countryName,
                                    value: item.name,
                                    stateOrProvince: item.adminName1,
                                    countryName: item.countryName
                                }
                            }));
                        }
                    });
                },
                minLength: 2,
                select: function( event, ui ) {
                    if (ui.item) {
                        $("#id_stateOrProvince").val(ui.item.stateOrProvince);
                        $("#id_country").val(ui.item.countryName);
                        $("#id_zipCode").val("");
                    }
                }
            });
        });
    </script>
<div class="text-center">
    <h1 ALIGN=center><strong>Create new User profile</strong></h1>
</div>
    <form method="post"  enctype="multipart/form-data">
        {% csrf_token %}
        <table ALIGN=center>
        {{ UserForm.as_table }}
        </table>
       <h1 ALIGN=center> <input  type="submit" name="submit" value="Guardar" ALIGN=center/></h1>


    </form>


{% endblock %}